### ISSUE TITLE
Function for creating a vanity url

### ISSUE THREAD

**Issue by gregoryagu** [microsoft/AzUrlShortener#453]
I am checking out the UrlRedirect project and indeed it does a redirect.

But how to create the vanity url?  In other words, I have a long url, and I want to create the short URL so that I can use it with the redirect.  I don't see a function for that in the project. (UrlShortner.cs)

Am I missing something?

**Comment by FBoucher** [comment]
@gregoryagu @sergebsv This has been fixed when we merge the TinyBlazorAdmin repo with this one. Today the Azure function can create, list, redirect, delete.
