### ISSUE TITLE
Documentation is not up to date

### ISSUE THREAD

**Issue by ShawnOlwig** [microsoft/AzUrlShortener#481]
I am curious if your URL Shortener is currently able to be deployed and in a working state? Your Documentation seems to be way out of date when it comes to trying to use the Blazor front end. The repo where it used to be located says it's been deprecated and moved to where the backend files are though I can't seem to find them or the updated instructions to deploy it. The current instructions that I can find seem to send you in circles. It tells you to Copy The Repo which I can't find, the next step is to deploy the backend but in the ARM form for the back end it says that you need to have the Existing SWA Name from deploying the front end...

**Comment by fboucheros** [comment]
Sorry @ShawnOlwig you are probably right. A lot moved around and the documentation probably needs to be review.

**Comment by asthypar** [comment]
@fboucheros I can definitely attest to this. I cannot see how we can deploy Blazor as it links to a deprecated project and sends you back to the AzUrlShortener project, which obviously sends you to the deprecated project again...

**Comment by pelletierr** [comment]
I can attest to this too. We are trying to figure things out to deploy it in our environnement.

**Comment by fboucheros** [comment]
@autrymt37 That would be cool right? You should create a feature request,I think it's a good idea.

**Comment by FBoucher** [comment]
@ShawnOlwig @asthypar @pelletierr I updated the documentation.

Following the [wiki: How-to-deploy-TinyBlazorAdmin](https://github.com/microsoft/AzUrlShortener/wiki/How-to-deploy-TinyBlazorAdmin) I was able to have the TinyBlazorAdmin deployed and the backend.

**Comment by FBoucher** [comment]
I will close this issue.
